server:
  port: ${vcap.application.port:8081}

management:
  cloudfoundry:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri:  https://kg-test-user-service.run.aws-usw02-pr.ice.predix.io
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<segment>.*), /$\{segment}
      - id: documentation-service
        uri:  https://kg-test-docs-service.run.aws-usw02-pr.ice.predix.io
        predicates:
        - Path=/docs/**
        filters:
        - RewritePath=/docs/(?<segment>.*), /$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8061}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}/
    secureVirtualHostName: https://${vcap.application.application_uris[0]}